apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf:
    upstream httpd_upstream {
      server 10.106.172.11:80;
    }

    server {
      listen 80;
      location / {
        proxy_pass http://httpd_upstream;
      }
    }