apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-httpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: "{{ .Values.httpd.image.repository }}:{{ .Values.httpd.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 6Mi
            limits:
              cpu: 12m
              memory: 10Mi
  
